/**
 * Maps the kebab-case `icon` values in `data/rates.json` to lucide components.
 *
 * The mapping is explicit rather than a dynamic `import()` for three reasons:
 * only the icons actually used are bundled, there is no per-icon network
 * request or loading state, and an unknown name is caught at build time by
 * TypeScript instead of rendering a blank space in production.
 *
 * Adding a new icon to data/rates.json means adding one line here. If that is
 * forgotten, `resolveIcon` falls back to a neutral package glyph rather than
 * crashing the page.
 *
 * A glyph may legitimately repeat across the list — "Brass" and "Brass
 * Utensils" are the same material — but two ADJACENT rows sharing one icon
 * reads as a copy-paste bug, so keep neighbours distinct.
 */

import {
  AirVent,
  Archive,
  Armchair,
  Barrel,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Bed,
  Beer,
  Bell,
  Bike,
  Blend,
  Blocks,
  Bolt,
  BookOpen,
  Box,
  Boxes,
  Cable,
  Calculator,
  Cctv,
  CircleDot,
  CircuitBoard,
  Coins,
  Component,
  Container,
  CookingPot,
  Copy,
  Cpu,
  CupSoda,
  Cylinder,
  Disc,
  Droplets,
  Fan,
  FileText,
  Files,
  Flame,
  Gamepad2,
  GlassWater,
  Hammer,
  HardDrive,
  Headphones,
  Keyboard,
  Laptop,
  Layers,
  LayoutGrid,
  Magnet,
  MemoryStick,
  Microwave,
  Milk,
  Monitor,
  MonitorSmartphone,
  Mouse,
  Newspaper,
  Package,
  Package2,
  PcCase,
  Pipette,
  Plug,
  PlugZap,
  Printer,
  Projector,
  Radio,
  Recycle,
  Refrigerator,
  Router,
  Scissors,
  Shirt,
  ShoppingBag,
  ShowerHead,
  Smartphone,
  Snowflake,
  Soup,
  Speaker,
  Square,
  Tablet,
  Tv,
  TvMinimal,
  Unplug,
  Usb,
  Utensils,
  Warehouse,
  WashingMachine,
  Watch,
  Weight,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'air-vent': AirVent,
  archive: Archive,
  armchair: Armchair,
  barrel: Barrel,
  bath: Bath,
  battery: Battery,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  'battery-low': BatteryLow,
  'battery-medium': BatteryMedium,
  bed: Bed,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  blend: Blend,
  blocks: Blocks,
  bolt: Bolt,
  'book-open': BookOpen,
  box: Box,
  boxes: Boxes,
  cable: Cable,
  calculator: Calculator,
  cctv: Cctv,
  'circle-dot': CircleDot,
  'circuit-board': CircuitBoard,
  coins: Coins,
  component: Component,
  container: Container,
  'cooking-pot': CookingPot,
  copy: Copy,
  cpu: Cpu,
  'cup-soda': CupSoda,
  cylinder: Cylinder,
  disc: Disc,
  droplets: Droplets,
  fan: Fan,
  'file-text': FileText,
  files: Files,
  flame: Flame,
  'gamepad-2': Gamepad2,
  'glass-water': GlassWater,
  hammer: Hammer,
  'hard-drive': HardDrive,
  headphones: Headphones,
  keyboard: Keyboard,
  laptop: Laptop,
  layers: Layers,
  'layout-grid': LayoutGrid,
  magnet: Magnet,
  'memory-stick': MemoryStick,
  microwave: Microwave,
  milk: Milk,
  monitor: Monitor,
  'monitor-smartphone': MonitorSmartphone,
  mouse: Mouse,
  newspaper: Newspaper,
  package: Package,
  'package-2': Package2,
  'pc-case': PcCase,
  pipette: Pipette,
  plug: Plug,
  'plug-zap': PlugZap,
  printer: Printer,
  projector: Projector,
  radio: Radio,
  recycle: Recycle,
  refrigerator: Refrigerator,
  router: Router,
  scissors: Scissors,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shower-head': ShowerHead,
  smartphone: Smartphone,
  snowflake: Snowflake,
  soup: Soup,
  speaker: Speaker,
  square: Square,
  tablet: Tablet,
  tv: Tv,
  'tv-minimal': TvMinimal,
  unplug: Unplug,
  usb: Usb,
  utensils: Utensils,
  warehouse: Warehouse,
  'washing-machine': WashingMachine,
  watch: Watch,
  weight: Weight,
  wifi: Wifi,
  wind: Wind,
  zap: Zap,
};

/** Icon for a `data/rates.json` icon name, falling back to a generic box. */
export function resolveIcon(name: string): LucideIcon {
  return iconMap[name] ?? Package;
}

/** One representative icon per rate category, for the "What we buy" grid. */
export const categoryIcons = {
  metals: Hammer,
  wires: Cable,
  paper: Newspaper,
  plastic: Milk,
  glass: GlassWater,
  battery: BatteryCharging,
  appliances: Refrigerator,
  computers: Laptop,
  mobile: Smartphone,
  ewaste: Recycle,
} as const;
