/**
 * JSON-LD builders.
 *
 * Every schema is derived from `siteConfig` or from the same arrays that render
 * the visible UI, so the structured data can never drift from what a human
 * actually sees on the page — which is exactly what Google penalises.
 */

import { siteConfig, activeSocials } from '@/lib/site-config';
import type { FaqItem, Locale } from '@/types';

/** Sitewide LocalBusiness. Rendered once, in the locale layout. */
export function buildLocalBusinessSchema(locale: Locale) {
  const isNe = locale === 'ne';

  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    '@id': `${siteConfig.url}/#business`,
    name: siteConfig.name,
    description: isNe
      ? 'काठमाडौं उपत्यकाभर कवाडी खरिद तथा निःशुल्क पिकअप सेवा।'
      : 'Scrap buying and free pickup service across Kathmandu Valley.',
    url: siteConfig.url,
    telephone: siteConfig.phone,
    email: siteConfig.email,
    priceRange: siteConfig.priceRange,
    // Locale-specific share card, generated by docs/make-og.py.
    image: `${siteConfig.url}/images/og-${locale}.png`,
    address: {
      '@type': 'PostalAddress',
      streetAddress: isNe ? siteConfig.addressNe : siteConfig.addressEn,
      addressLocality: isNe ? 'काठमाडौं' : 'Kathmandu',
      addressRegion: isNe ? 'बागमती' : 'Bagmati',
      addressCountry: 'NP',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: siteConfig.geo.lat,
      longitude: siteConfig.geo.lng,
    },
    areaServed: siteConfig.coverage.map((area) => ({
      '@type': 'City',
      name: isNe ? area.nameNe : area.nameEn,
    })),
    openingHoursSpecification: siteConfig.hours.map((slot) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: slot.days,
      opens: slot.opens,
      closes: slot.closes,
    })),
    sameAs: activeSocials().map((social) => social.href),
  };
}

/** WebSite schema for the homepage. */
export function buildWebSiteSchema(locale: Locale) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${siteConfig.url}/#website`,
    url: `${siteConfig.url}/${locale}`,
    name: siteConfig.name,
    inLanguage: locale === 'ne' ? 'ne-NP' : 'en-NP',
    publisher: { '@id': `${siteConfig.url}/#business` },
  };
}

/** FAQPage, built from the very array that renders the accordion. */
export function buildFaqSchema(items: FaqItem[], locale: Locale) {
  const isNe = locale === 'ne';

  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: isNe ? item.questionNe : item.questionEn,
      acceptedAnswer: {
        '@type': 'Answer',
        text: isNe ? item.answerNe : item.answerEn,
      },
    })),
  };
}

/** BreadcrumbList for inner pages. */
export function buildBreadcrumbSchema(
  crumbs: { name: string; path: string }[],
  locale: Locale,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: `${siteConfig.url}/${locale}${crumb.path}`,
    })),
  };
}
