/**
 * JSON-LD builders.
 *
 * Every schema is derived from `siteConfig` or from the same arrays that render
 * the visible UI, so the structured data can never drift from what a human
 * actually sees on the page — which is exactly what Google penalises.
 */

import { siteConfig, activeSocials, absoluteUrl } from '@/lib/site-config';
import { buildWhatsAppUrl } from '@/lib/whatsapp';
import type { FaqItem, Locale } from '@/types';

/**
 * Everywhere Google can see the business is the same business.
 *
 * `sameAs` is the strongest non-Maps signal that this website and a Google
 * Business Profile describe one entity, so it must never be an empty array —
 * an empty `sameAs` is worse than none at all. Until the real Facebook and
 * TikTok URLs are filled into `site-config.ts`, the WhatsApp deep link is the
 * one genuinely public profile this business has, so it stands in.
 */
function sameAsProfiles(): string[] {
  const socials = activeSocials().map((social) => social.href);
  return socials.length > 0 ? socials : [buildWhatsAppUrl()];
}

/**
 * Sitewide LocalBusiness. Rendered once, in the locale layout.
 *
 * The dual `@type` is deliberate. `LocalBusiness` is what earns the map pack
 * and the knowledge panel; `RecyclingCenter` is the specific subtype that tells
 * Google *what kind* of local business this is, which is what matches a query
 * like "scrap buyer kathmandu" to this entity rather than to a hardware shop.
 * Both are declared because dropping the generic type would cost the generic
 * local-business treatment.
 */
export function buildLocalBusinessSchema(locale: Locale) {
  const isNe = locale === 'ne';

  return {
    '@context': 'https://schema.org',
    '@type': ['LocalBusiness', 'RecyclingCenter'],
    '@id': `${siteConfig.url}/#business`,
    name: siteConfig.name,
    // `name` is always the Latin form, so the Devanagari spelling is listed
    // unconditionally — it is how a Nepali-language searcher types the brand,
    // and entity matching needs to see both.
    alternateName: ['केटीएम कवाडी', 'KTM Kabadi'],
    description: isNe
      ? 'काठमाडौं उपत्यकाभर कवाडी खरिद तथा निःशुल्क पिकअप सेवा।'
      : 'Kawadi (scrap) buying and free doorstep pickup service across Kathmandu Valley — copper, brass, iron, aluminium, paper, plastic, batteries and e-waste.',
    url: absoluteUrl(`/${locale}`),
    telephone: siteConfig.phoneTel,
    email: siteConfig.email,
    priceRange: siteConfig.priceRange,
    currenciesAccepted: 'NPR',
    paymentAccepted: isNe ? 'नगद, बैंक ट्रान्सफर' : 'Cash, Bank transfer',
    knowsLanguage: ['en', 'ne'],
    // Locale-specific share card, generated by docs/make-og.py.
    image: `${siteConfig.url}/images/og-${locale}.png`,
    logo: `${siteConfig.url}/logo-mark.png`,
    address: {
      '@type': 'PostalAddress',
      streetAddress: isNe ? siteConfig.addressNe : siteConfig.addressEn,
      addressLocality: isNe ? 'काठमाडौं' : 'Kathmandu',
      addressRegion: isNe ? 'बागमती' : 'Bagmati',
      addressCountry: 'NP',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: siteConfig.geo.lat,
      longitude: siteConfig.geo.lng,
    },
    areaServed: siteConfig.coverage.map((area) => ({
      '@type': 'City',
      name: isNe ? area.nameNe : area.nameEn,
    })),
    openingHoursSpecification: siteConfig.hours.map((slot) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: slot.days,
      opens: slot.opens,
      closes: slot.closes,
    })),
    sameAs: sameAsProfiles(),
  };
}

/**
 * The pickup service itself, as a distinct Service entity.
 *
 * LocalBusiness answers "who and where"; Service answers "what you can buy from
 * them", which is the half that matches an intent query like "kawadi pickup
 * nepal". `provider` points at the LocalBusiness @id so the two resolve to one
 * graph rather than two unrelated things.
 */
export function buildServiceSchema(locale: Locale) {
  const isNe = locale === 'ne';

  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': `${siteConfig.url}/#pickup-service`,
    serviceType: isNe
      ? 'कवाडी संकलन तथा पिकअप सेवा'
      : 'Kawadi (scrap) collection and pickup service',
    name: isNe
      ? 'काठमाडौंमा निःशुल्क कवाडी पिकअप'
      : 'Free kawadi & scrap pickup in Kathmandu',
    description: isNe
      ? 'काठमाडौं उपत्यकाभर घरायसी, कार्यालय र औद्योगिक कवाडी निःशुल्क पिकअप। तपाईंकै अगाडि तौल, तुरुन्तै नगद भुक्तानी।'
      : 'Free household, office and industrial kawadi pickup across Kathmandu Valley. Weighed in front of you, cash paid on the spot.',
    provider: { '@id': `${siteConfig.url}/#business` },
    areaServed: siteConfig.coverage.map((area) => ({
      '@type': 'City',
      name: isNe ? area.nameNe : area.nameEn,
    })),
    availableChannel: {
      '@type': 'ServiceChannel',
      servicePhone: siteConfig.phoneTel,
      serviceUrl: absoluteUrl(`/${locale}/contact`),
    },
    offers: {
      '@type': 'Offer',
      priceCurrency: 'NPR',
      // The pickup is free; what varies is the rate paid for the material,
      // which lives on /rates rather than being claimable as a single price.
      price: '0',
      url: absoluteUrl(`/${locale}/rates`),
      availability: 'https://schema.org/InStock',
    },
  };
}

/** WebSite schema for the homepage. */
export function buildWebSiteSchema(locale: Locale) {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${siteConfig.url}/#website`,
    url: absoluteUrl(`/${locale}`),
    name: siteConfig.name,
    inLanguage: locale === 'ne' ? 'ne-NP' : 'en-NP',
    publisher: { '@id': `${siteConfig.url}/#business` },
  };
}

/** FAQPage, built from the very array that renders the accordion. */
export function buildFaqSchema(items: FaqItem[], locale: Locale) {
  const isNe = locale === 'ne';

  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: isNe ? item.questionNe : item.questionEn,
      acceptedAnswer: {
        '@type': 'Answer',
        text: isNe ? item.answerNe : item.answerEn,
      },
    })),
  };
}

/** BreadcrumbList for inner pages. */
export function buildBreadcrumbSchema(
  crumbs: { name: string; path: string }[],
  locale: Locale,
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(`/${locale}${crumb.path}`),
    })),
  };
}
